language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  distributions: sdist
  user: mrbot
  password:
    secure: HnQ6jX8CVlCZnCl3Zd3TUTFA2hqrXDVm31YxMjHv9BGAO6+bTG6Rkym0YIKRTGt9K6qCN2CwOQEUqSrW+xB2DVP1WhDim3TQ1zP+VdYAkT7tr28i1doahY0tL7H7AnB3oteV6wRXMSSvVt6Fdhp8KsyM/R3ZL6Y3ZRFt3KyFG6+sbInnI3JLjlH7pLcvjoZGjE10TjvFWvZ7w0wVapC9KzaafM1Uxu2EQKy/BADKXDY5gRAm5V0JX8f9b/F9HLH3647AoMtyFOWuFcPO87FMlnkxfT1tcN7scHmfS9irSgeyrZMTQRi0YOcz33yi0nhGfCoQ92n3ABQjXwkC0YcoWOgJkS+bUPF7Y4vRum834NfdXhHcDDNmCR73c8Xf6S7FUgP0dIGJV+KGCB/NukkwV9/PxoN42pErQNSXcB2i3aUMPBo6aEuc7r45zYXp1Q1Ga02iFokqzr6/auhZRBvU278TuRnTJNJ/4yuM9XIatj92ciOY1WmD57BgjIFCHj9OsX79giQAk5IrltmTKNtuC6oHpHgkB2mvfU49THvjBWFzh5CTw9lf+pLQq8Pm5S1pWwc7luHTlFJBcQg+ijnpQe+yvn8buf8x6ohKnwuYu26DzuaKUjrA+HoTzYTqzWHbHVdSR+9gIWwB1JWKp8PxKcMFK7CNKNwdAwgf+sGLLW8=
  on:
    tags: true
    python: 3.6
