language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  distributions: sdist
  user: mrbot
  password:
    secure: EPJcaszo40s/OfThooXHVDaE35ikY7yce3eBGf6uqfy/Oa7CnG+uMC1F2ETo9LS8/GkL6ouccy4eAUfQ8NDd2Wl1KDPY90sOw2g/ehDsPRH/MDYD8ATtLv4OP9AbxxV2y4pZ0ieKqzeefdCQiZGKGI6TO4ufKIEOXH6tHHFLPaoDDdv4tEPCMWEh22iNtkwUwbX4ljE1S+ka5SfngB/UeTLiIDpUUlKcK4c3gggA71dh2czVOo9ykB1qITcu9LmX+RzS0peZxoQisqMbxUttGQ931H1N5SMfJukNdoyiCwGT5l3KbqVZ5roPEnls9kFIr06DWuvo/HYR3kJcgjZqVknUSQMiddLws/bVzxYfJQGyqC4RsnGAaiKlGOAy3rUjLkKJzjEmAE2uOnMEgwIi0A4+Qcig8Qadgu5BBnZzSuRpgGzC59nRUlnZYiyfewY40X3QeawZ1plIkmN/lN/pOBeIlu6Ms1qLempmJ5V+aduGDSOJ43H3Y78L9m+1Us6+5zYWRqheHPjWYk09KCgmVopW8kjEvY9ZLkjr0Ufzd3fgvpI8/74k1UPBp27FV3IrqgKWEjqKMtmXeXS8+APKV1rjDfsR5qjAjKkqLXbO4RUg4QuS+zQAazOo0wccsh7e6gxnT08rw4m2+DroVcsN+pftkzsAVDhMS0KlvirGlh8=
  on:
    tags: true
    python: 3.6

